-- generated by `arc psqldb migrate` for plugin 'relay'

-- (schema) _job_log: DROP NOT NULL on "started_at"
ALTER TABLE "_job_log" ALTER COLUMN "started_at" DROP NOT NULL;

-- (schema) _job_log: DROP NOT NULL on "finished_at"
ALTER TABLE "_job_log" ALTER COLUMN "finished_at" DROP NOT NULL;

-- (schema) _job_log: DROP NOT NULL on "duration_ms"
ALTER TABLE "_job_log" ALTER COLUMN "duration_ms" DROP NOT NULL;

-- (schema) _job_log: ADD COLUMN "task_id" (STRING)
ALTER TABLE "_job_log" ADD COLUMN "task_id" VARCHAR(64);

-- (schema) _job_log: ensure index "idx_job_log_finished_at"
CREATE INDEX IF NOT EXISTS "idx_job_log_finished_at" ON "_job_log" ("finished_at");

-- (schema) _job_log: ensure index "idx_job_log_task_name"
CREATE INDEX IF NOT EXISTS "idx_job_log_task_name" ON "_job_log" ("task_name");

-- (schema) _job_log: ensure index "idx_job_log_request_id"
CREATE INDEX IF NOT EXISTS "idx_job_log_request_id" ON "_job_log" ("request_id");

-- (schema) _job_log: ensure index "idx_job_log_task_id"
CREATE INDEX IF NOT EXISTS "idx_job_log_task_id" ON "_job_log" ("task_id");
