-- generated by `arc psqldb migrate` for plugin 'relay'

-- (schema) CREATE TABLE "_job_log" (11 fields)
CREATE TABLE IF NOT EXISTS "_job_log" (
    "id" UUID PRIMARY KEY DEFAULT arc_uuid_generate_v7(),
    "task_name" VARCHAR(255) NOT NULL,
    "queue" VARCHAR(64) NOT NULL,
    "executor" VARCHAR(255) NOT NULL,
    "job_type" VARCHAR(255) NOT NULL,
    "queued_by" VARCHAR(100),
    "status" VARCHAR(255) NOT NULL,
    "error" TEXT,
    "started_at" TIMESTAMPTZ NOT NULL,
    "finished_at" TIMESTAMPTZ NOT NULL,
    "duration_ms" INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_job_log_finished_at" ON "_job_log" ("finished_at");
CREATE INDEX IF NOT EXISTS "idx_job_log_task_name" ON "_job_log" ("task_name");
