-- generated by `arc psqldb migrate` for plugin 'relay'

-- (schema) _job_log: ensure index "idx_job_log_finished_at"
CREATE INDEX IF NOT EXISTS "idx_job_log_finished_at" ON "_job_log" ("finished_at");

-- (schema) _job_log: ensure index "idx_job_log_task_name"
CREATE INDEX IF NOT EXISTS "idx_job_log_task_name" ON "_job_log" ("task_name");
