-- generated by `arc psqldb migrate` for plugin 'relay'

-- (schema) _job_log: ADD COLUMN "request_id" (STRING)
ALTER TABLE "_job_log" ADD COLUMN "request_id" VARCHAR(128);

-- (schema) _job_log: ADD COLUMN "triggered_by" (STRING)
ALTER TABLE "_job_log" ADD COLUMN "triggered_by" VARCHAR(255);

-- (schema) _job_log: ensure index "idx_job_log_finished_at"
CREATE INDEX IF NOT EXISTS "idx_job_log_finished_at" ON "_job_log" ("finished_at");

-- (schema) _job_log: ensure index "idx_job_log_task_name"
CREATE INDEX IF NOT EXISTS "idx_job_log_task_name" ON "_job_log" ("task_name");

-- (schema) _job_log: ensure index "idx_job_log_request_id"
CREATE INDEX IF NOT EXISTS "idx_job_log_request_id" ON "_job_log" ("request_id");
